# Generated by Django 3.1.5 on 2021-01-11 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblistInquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='사용자 명')),
                ('email', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('content', models.CharField(max_length=2000)),
                ('is_send_email', models.BooleanField(default=False)),
                ('send_email_date', models.DateTimeField(null=True)),
                ('is_answer', models.BooleanField(default=False)),
                ('reg_user', models.CharField(max_length=20, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('0', '오류신고'), ('1', '기능개선'), ('2', '데이터 문의'), ('3', '답변')], default='0', max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tblistinquire', verbose_name='부모id')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblist_inquire',
            },
        ),
    ]
